/*
 * Browser-only demo data layer. All records live in this browser's localStorage;
 * no API server, database, or secrets are required to run the Vercel demo.
 * Uploaded files are represented by metadata only. The demo pipeline is a
 * clearly-labelled simulation and must not be used to make official decisions.
 */
const STORE = 'bhoomi_demo_v1';
const demoUsers = [
  {id:1,username:'superadmin',full_name:'Aarav Mehta',email:'superadmin@bhoomi.demo',role:'super_admin',is_active:true,department:'Revenue Department',state:'Uttar Pradesh',district:'Kanpur Nagar',tehsil:'Bilhaur'},
  {id:2,username:'admin',full_name:'Ananya Rao',email:'admin@bhoomi.demo',role:'admin',is_active:true,department:'Revenue Department',state:'Uttar Pradesh',district:'Kanpur Nagar',tehsil:'Bilhaur'},
  {id:3,username:'district_officer',full_name:'Rohan Verma',email:'district_officer@bhoomi.demo',role:'district_officer',is_active:true,department:'Revenue Department',state:'Uttar Pradesh',district:'Kanpur Nagar',tehsil:'Bilhaur'},
  {id:4,username:'tehsil_officer',full_name:'Kavita Singh',email:'tehsil_officer@bhoomi.demo',role:'tehsil_officer',is_active:true,department:'Revenue Department',state:'Uttar Pradesh',district:'Kanpur Nagar',tehsil:'Bilhaur'},
  {id:5,username:'verification_officer',full_name:'Priya Sharma',email:'verification_officer@bhoomi.demo',role:'verification_officer',is_active:true,department:'Revenue Department',state:'Uttar Pradesh',district:'Kanpur Nagar',tehsil:'Bilhaur'},
  {id:6,username:'viewer',full_name:'Public Viewer',email:'viewer@bhoomi.demo',role:'viewer',is_active:true,department:'Public Portal',state:'',district:'',tehsil:''}
];
const seed = () => {
  const docs = [
    { id: 101, file_name: 'khatauni_bilhaur_2024.pdf', document_type: 'khatauni', document_year: 2024, state: 'Uttar Pradesh', district: 'Kanpur Nagar', tehsil: 'Bilhaur', village: 'Bilhaur Dehat', status: 'verification_pending', ocr_confidence: .91, extraction_confidence: .86, page_count: 3, created_at: '2026-09-27T10:15:00Z', parcel_id: 1, extracted_fields: [{standardized_field:'owner_name',field_value:'Sita Devi',confidence:.94},{standardized_field:'khasra_number',field_value:'142/2',confidence:.97},{standardized_field:'khata_number',field_value:'0087',confidence:.91},{standardized_field:'area',field_value:'1.240 hectare',confidence:.81},{standardized_field:'land_type',field_value:'Agricultural',confidence:.88}] },
    { id: 102, file_name: 'mutation_register_kanpur.pdf', document_type: 'mutation_register', document_year: 2022, state: 'Uttar Pradesh', district: 'Kanpur Nagar', tehsil: 'Bilhaur', village: 'Bilhaur Dehat', status: 'verification_pending', ocr_confidence: .78, extraction_confidence: .72, page_count: 5, created_at: '2026-09-26T08:20:00Z', parcel_id: 1, extracted_fields: [{standardized_field:'owner_name',field_value:'Ram Kumar',confidence:.70},{standardized_field:'khasra_number',field_value:'142/2',confidence:.94},{standardized_field:'area',field_value:'1.240 hectare',confidence:.86}] },
    { id: 103, file_name: 'sale_deed_jaipur_2023.pdf', document_type: 'sale_deed', document_year: 2023, state: 'Rajasthan', district: 'Jaipur', tehsil: 'Sanganer', village: 'Shivdaspura', status: 'verified', ocr_confidence: .95, extraction_confidence: .92, page_count: 8, created_at: '2026-09-25T12:00:00Z', parcel_id: 2, extracted_fields: [{standardized_field:'owner_name',field_value:'Meera Sharma',confidence:.96},{standardized_field:'khasra_number',field_value:'88/1',confidence:.95},{standardized_field:'area',field_value:'0.860 hectare',confidence:.90}] },
    { id: 104, file_name: 'jamabandi_ludhiana_2021.pdf', document_type: 'jamabandi', document_year: 2021, state: 'Punjab', district: 'Ludhiana', tehsil: 'Samrala', village: 'Manupur', status: 'processed', ocr_confidence: .89, extraction_confidence: .83, page_count: 2, created_at: '2026-09-24T09:45:00Z', parcel_id: 3, extracted_fields: [{standardized_field:'owner_name',field_value:'Gurpreet Singh',confidence:.91},{standardized_field:'khasra_number',field_value:'31//4',confidence:.88},{standardized_field:'area',field_value:'2.100 hectare',confidence:.82}] },
    { id: 105, file_name: 'patta_chitta_chennai.pdf', document_type: 'patta', document_year: 2020, state: 'Tamil Nadu', district: 'Chennai', tehsil: 'Alandur', village: 'Nanganallur', status: 'verified', ocr_confidence: .93, extraction_confidence: .90, page_count: 4, created_at: '2026-09-22T11:30:00Z', parcel_id: 4, extracted_fields: [{standardized_field:'owner_name',field_value:'Arun Kumar',confidence:.95},{standardized_field:'khasra_number',field_value:'216/7',confidence:.91},{standardized_field:'area',field_value:'480 sq.m',confidence:.89}] }
  ];
  const parcels = [
    {id:1,khasra_number:'142/2',khata_number:'0087',owner_name:'Sita Devi',area:'1.240 hectare',land_type:'Agricultural',state:'Uttar Pradesh',district:'Kanpur Nagar',tehsil:'Bilhaur',village:'Bilhaur Dehat',sufficiency_score:68,status:'REVIEW_REQUIRED'},
    {id:2,khasra_number:'88/1',khata_number:'0142',owner_name:'Meera Sharma',area:'0.860 hectare',land_type:'Residential',state:'Rajasthan',district:'Jaipur',tehsil:'Sanganer',village:'Shivdaspura',sufficiency_score:92,status:'VERIFIED'},
    {id:3,khasra_number:'31//4',khata_number:'0220',owner_name:'Gurpreet Singh',area:'2.100 hectare',land_type:'Agricultural',state:'Punjab',district:'Ludhiana',tehsil:'Samrala',village:'Manupur',sufficiency_score:81,status:'IN_PROGRESS'},
    {id:4,khasra_number:'216/7',khata_number:'0911',owner_name:'Arun Kumar',area:'480 sq.m',land_type:'Residential',state:'Tamil Nadu',district:'Chennai',tehsil:'Alandur',village:'Nanganallur',sufficiency_score:95,status:'VERIFIED'}
  ];
  return { docs, parcels, findings:[{id:1,document_id:102,parcel_id:1,rule_name:'Ownership continuity',message:'Owner name differs between the 2022 mutation entry and 2024 khatauni. Confirm the supporting transfer deed.',severity:'error',status:'open'},{id:2,document_id:101,parcel_id:1,rule_name:'Area consistency',message:'Area matches the prior record; supporting map sheet is not linked.',severity:'warning',status:'open'},{id:3,document_id:104,parcel_id:3,rule_name:'Low confidence field',message:'OCR confidence on the owner name is below the review threshold.',severity:'warning',status:'open'}], cases:[{id:1,parcel_id:1,status:'OPEN',priority_score:86,priority_band:'HIGH',title:'Ownership chain needs review',assigned_to:null,comments:[]}], records:[{id:501,document_id:103,parcel_id:2,owner_name:'Meera Sharma',khasra_number:'88/1',khata_number:'0142',area:'0.860',area_unit:'hectare',land_type:'Residential',land_classification:'Residential',state:'Rajasthan',district:'Jaipur',tehsil:'Sanganer',village:'Shivdaspura',status:'verified',verification_status:'verified',year:2023},{id:502,document_id:105,parcel_id:4,owner_name:'Arun Kumar',khasra_number:'216/7',area:'480',area_unit:'sq.m',land_type:'Residential',land_classification:'Residential',state:'Tamil Nadu',district:'Chennai',tehsil:'Alandur',village:'Nanganallur',status:'verified',verification_status:'verified',year:2020}], audit:[], users:demoUsers.map(u=>({...u})), notifications:[{id:1,title:'Review required',message:'Parcel 142/2 has an ownership discrepancy awaiting review.',is_read:false,created_at:'2026-09-27T10:15:00Z'}], nextDoc:106, nextRecord:503};
};
const getStore = () => {
  try {
    const saved = localStorage.getItem(STORE);
    if (saved) {
      const value = JSON.parse(saved);
      if (!Array.isArray(value.users) || value.users.length === 0) value.users = demoUsers.map((u) => ({ ...u }));
      if (Array.isArray(value.findings)) value.findings = value.findings.map((f) => ({ ...f, resolution_status: f.resolution_status || (f.status === 'resolved' ? 'RESOLVED' : 'OPEN') }));
      save(value);
      return value;
    }
  } catch {}
  const value = seed();
  save(value);
  return value;
};
const save = (value) => localStorage.setItem(STORE, JSON.stringify(value));
const qs = (path) => { const [url,query='']=path.split('?'); return {url,params:Object.fromEntries(new URLSearchParams(query))}; };
const ok = (data) => ({data,status:200,headers:{},config:{}});
const userFor = (username) => { const rows={superadmin:['super_admin','Aarav Mehta'],admin:['admin','Ananya Rao'],district_officer:['district_officer','Rohan Verma'],tehsil_officer:['tehsil_officer','Kavita Singh'],verification_officer:['verification_officer','Priya Sharma'],viewer:['viewer','Public Viewer']}; const [role,full_name]=rows[username]||rows.verification_officer; return {id:username,username,role,full_name,email:`${username}@bhoomi.demo`,is_active:true}; };
const claimsForDocument = (doc) => (doc.extracted_fields || []).map((field, index) => ({ ...field, id: doc.id * 1000 + index + 1, document_id: doc.id, field_value: field.field_value, source_text: field.field_value, asserted_by: 'SYSTEM', lifecycle_status: 'ACCEPTED', confidence_basis: 'Illustrative demo confidence' }));
const demo = async (method,rawPath,data,config={}) => {
  await new Promise(r=>setTimeout(r,160));
  const {url,params:queryParams={}}=qs(rawPath); const params={...queryParams,...(config.params||{})}; const p=url.replace(/^\/api\/v1/,'').replace(/\/$/,'')||'/'; const s=getStore(); const idMatch=p.match(/\/(\d+)(?:\/|$)/); const id=idMatch?Number(idMatch[1]):null;
  const log=(action,details={})=>{s.audit.unshift({id:Date.now(),action,details,created_at:new Date().toISOString(),user:localStorage.getItem('bhoomi_user')?JSON.parse(localStorage.getItem('bhoomi_user')).username:'demo'});save(s);};
  let result=[];
  if(p==='/auth/login'&&method==='post'){if(!data?.username||!data?.password)throw {response:{status:401,data:{detail:'Enter a username and password.'}}};result={access_token:'browser-demo-session',user:userFor(data.username)};}
  else if(p==='/auth/logout') result={ok:true};
  else if(p==='/processing/engine-status') result={available:true,engine:'Demo simulation',version:'browser',supported_language_count:12,supported_iso_languages:['eng','hin','tam','tel','kan','ben','mar','guj','pan','ori','mal','asm']};
  else if(p==='/dashboard/stats'){const docs=s.docs;result={total_documents:docs.length,processed_documents:docs.filter(d=>d.status!=='uploaded').length,verified_documents:docs.filter(d=>d.status==='verified').length,pending_verification:docs.filter(d=>d.status==='verification_pending').length,open_findings:s.findings.filter(f=>f.status==='open').length,average_ocr_confidence:88,average_extraction_confidence:84,processing_timeline:[{day:'Mon',uploaded:5,verified:2},{day:'Tue',uploaded:8,verified:5},{day:'Wed',uploaded:6,verified:3},{day:'Thu',uploaded:10,verified:7},{day:'Fri',uploaded:7,verified:5},{day:'Sat',uploaded:4,verified:3},{day:'Sun',uploaded:6,verified:4}],status_distribution:[{name:'Verified',value:docs.filter(d=>d.status==='verified').length,color:'#059669'},{name:'Pending',value:docs.filter(d=>d.status==='verification_pending').length,color:'#f59e0b'},{name:'Processed',value:docs.filter(d=>d.status==='processed').length,color:'#3b82f6'}],state_progress:[{state:'Uttar Pradesh',total:32,verified:22},{state:'Rajasthan',total:26,verified:19},{state:'Punjab',total:18,verified:12},{state:'Tamil Nadu',total:24,verified:18}],confidence_distribution:[{range:'90–100%',count:2},{range:'80–89%',count:2},{range:'70–79%',count:1},{range:'Below 70%',count:0}]};}
  else if(p==='/dashboard/public-summary') result={verified_land_records:s.records.length,verified_gis_parcels:s.parcels.length};
  else if(p==='/documents/upload'&&method==='post'){const f=data?.get?.('file');const doc={id:s.nextDoc++,file_name:f?.name||'uploaded-record.pdf',document_type:data?.get?.('document_type')||'khatauni',document_year:Number(data?.get?.('document_year')||2024),state:data?.get?.('state')||'Uttar Pradesh',district:data?.get?.('district')||'Kanpur Nagar',tehsil:data?.get?.('tehsil')||'Bilhaur',village:data?.get?.('village')||'Bilhaur Dehat',status:'uploaded',ocr_confidence:null,extraction_confidence:null,page_count:1,created_at:new Date().toISOString(),parcel_id:1,extracted_fields:[]};s.docs.unshift(doc);save(s);log('Document uploaded', {document_id:doc.id,file_name:doc.file_name});result=doc;}
  else if(p==='/documents'&&method==='get') result=s.docs.filter(d=>!params.status||d.status===params.status).slice(0,Number(params.limit)||100);
  else if(/^\/documents\/\d+$/.test(p)&&method==='get') result=s.docs.find(d=>d.id===id)||{};
  else if(/^\/documents\/\d+$/.test(p)&&method==='delete'){s.docs=s.docs.filter(d=>d.id!==id);save(s);log('Document deleted',{document_id:id});result={ok:true};}
  else if(p.startsWith('/documents/')&&p.includes('/pages/')){result=new Blob(['<svg xmlns="http://www.w3.org/2000/svg" width="720" height="920" viewBox="0 0 720 920"><rect width="720" height="920" fill="#f8f5eb"/><rect x="48" y="48" width="624" height="824" fill="none" stroke="#9a8d70" stroke-width="2"/><text x="360" y="420" text-anchor="middle" font-family="sans-serif" font-size="28" fill="#475569">BHOOMI AI · DEMO PREVIEW</text><text x="360" y="466" text-anchor="middle" font-family="sans-serif" font-size="18" fill="#64748b">Illustrative page — not an uploaded source</text></svg>'],{type:'image/svg+xml'});}
  else if(p.startsWith('/processing/')&&p.endsWith('/start')){const doc=s.docs.find(d=>d.id===id);if(doc){doc.status='verification_pending';doc.ocr_confidence=.88;doc.extraction_confidence=.82;doc.extracted_fields=[{standardized_field:'owner_name',field_value:'Demo owner — confirm against source',confidence:.82},{standardized_field:'khasra_number',field_value:'142/2',confidence:.93},{standardized_field:'area',field_value:'1.240 hectare',confidence:.79}];save(s);log('Demo processing completed',{document_id:id});}result={detected_language_name:'Hindi (demo)',language_confidence:.96,ocr_confidence:.88,fields_extracted:3,anomalies_found:1,disclaimer:'Simulated demo output; not real OCR.'};}
  else if(p.startsWith('/processing/')&&p.endsWith('/translate')) result={ok:true};
  else if(p==='/verification/queue')result=s.docs.filter(d=>d.status==='verification_pending').map(d=>{const anomalies=s.findings.filter(f=>f.document_id===d.id&&f.status==='open');return {...d,anomalies,anomalies_count:anomalies.length,validation_status:anomalies.length?'warning':'valid'};});
  else if(p.startsWith('/verification/')&&p.endsWith('/submit')&&method==='post'){const doc=s.docs.find(d=>d.id===id);if(doc){doc.status=['approve','edited_approved'].includes(data?.action)?'verified':data?.action==='rejected'?'rejected':'verification_pending';doc.extracted_fields=(doc.extracted_fields||[]).map(f=>({...f,field_value:data?.corrected_fields?.[f.standardized_field]??f.field_value}));if(doc.status==='verified')s.records.unshift({id:s.nextRecord++,document_id:id,parcel_id:doc.parcel_id,owner_name:doc.extracted_fields.find(f=>f.standardized_field==='owner_name')?.field_value||'Reviewed owner',khasra_number:doc.extracted_fields.find(f=>f.standardized_field==='khasra_number')?.field_value||'—',khata_number:'—',area:doc.extracted_fields.find(f=>f.standardized_field==='area')?.field_value||'—',area_unit:'',land_type:'Agricultural',land_classification:'Agricultural',state:doc.state,district:doc.district,tehsil:doc.tehsil,village:doc.village,status:'verified',verification_status:'verified',year:doc.document_year});save(s);log(`Verification ${doc.status}`,{document_id:id,notes:data?.notes});}result={ok:true};}
  else if(p.startsWith('/verification/')&&p.includes('/claims/')&&p.endsWith('/correct')&&method==='post'){const claimId=Number(p.match(/\/claims\/(\d+)/)?.[1]);const doc=s.docs.find(d=>claimsForDocument(d).some(c=>c.id===claimId));if(doc){const claimIndex=claimsForDocument(doc).findIndex(c=>c.id===claimId);doc.extracted_fields[claimIndex].field_value=data?.new_value;save(s);log('Claim corrected',{document_id:doc.id,claim_id:claimId,new_value:data?.new_value});}result={status:'updated',new_claim:{id:claimId,claim_value:data?.new_value}};}
  else if(p.startsWith('/claims/')&&p.endsWith('/evidence')){const doc=s.docs.find(d=>claimsForDocument(d).some(c=>c.id===id));const claim=doc&&claimsForDocument(doc).find(c=>c.id===id);result=claim?{claim,document:{id:doc.id,file_name:doc.file_name,source_class:'SEED_SYNTHETIC'},evidence_available:false,no_evidence_reason:'Demo records do not include real scanned page evidence.'}:{claim:{id,standardized_field:'unknown',field_value:'Unavailable',confidence:null,asserted_by:'SYSTEM',lifecycle_status:'RETIRED'},document:null,evidence_available:false,no_evidence_reason:'The demo claim could not be found.'};}
  else if(p.startsWith('/findings/')&&p.endsWith('/resolve')&&method==='post'){const finding=s.findings.find(f=>f.id===id);if(finding){finding.resolution_status=data?.resolution_status||'RESOLVED';finding.resolution_note=data?.resolution_note||'';if(['RESOLVED','DISMISSED'].includes(finding.resolution_status))finding.status='resolved';save(s);}log('Finding updated',{finding_id:id,status:data?.resolution_status,note:data?.resolution_note});result=finding||{ok:true};}
  else if(p==='/validation/anomalies')result=s.findings.filter(f=>f.status==='open'&&(!params.severity||f.severity===params.severity)).slice(0,Number(params.limit)||100);
  else if(p.startsWith('/validation/resolve/')&&method==='put'){const f=s.findings.find(x=>x.id===id);if(f){f.status='resolved';f.resolution_status='RESOLVED';f.resolution_note=params.reason||'';}save(s);log('Finding resolved',{finding_id:id,reason:params.reason});result={ok:true};}
  else if(p==='/records')result=s.records.filter(r=>!params.state||r.state===params.state);
  else if(p.startsWith('/records/')&&p.endsWith('/history'))result={events:[{year:2020,event:'Record digitized'},{year:2023,event:'Officer verified'}]};
  else if(p==='/parcels'&&method==='get'){const q=(params.q||config.params?.q||'').toLowerCase();result={parcels:s.parcels.filter(a=>!q||JSON.stringify(a).toLowerCase().includes(q))};}
  else if(p.startsWith('/parcels/')&&p.endsWith('/timeline'))result={snapshots:[{as_of_year:2018,owner_name:'Ram Kumar',area:1.24,area_unit:'hectare',claims:[]},{as_of_year:2022,owner_name:'Ram Kumar',area:1.24,area_unit:'hectare',claims:[]},{as_of_year:2024,owner_name:'Sita Devi',area:1.24,area_unit:'hectare',claims:[]}],transitions:[{from_year:2018,to_year:2022,is_material:false,ownership_delta:null,area_delta_abs:0},{from_year:2022,to_year:2024,is_material:true,ownership_delta:'Owner changed from Ram Kumar to Sita Devi',area_delta_abs:0,explained_by_event_id:null}]};
  else if(p.startsWith('/parcels/')&&p.endsWith('/findings'))result={findings:s.findings.filter(f=>f.parcel_id===id).map(f=>({...f,finding_type:f.finding_type||(f.id===1?'CONTRADICTION':'EVIDENCE_GAP'),resolution_status:f.resolution_status||'OPEN',explanation:f.explanation||f.message,recommended_action:f.recommended_action||'Review the linked records and document the officer decision.',source_claim_ids:f.source_claim_ids||[]}))};
  else if(p.startsWith('/parcels/')&&p.endsWith('/sufficiency'))result={overall_score:.68,formula_version:'demo-v1',computed_at:new Date().toISOString(),components:{extraction_quality:{available:true,value:.82,weight:.2},cross_document_agreement:{available:true,value:.7,weight:.2},temporal_continuity:{available:true,value:.55,weight:.2},event_evidence:{available:false,value:null,weight:.15,basis:'No event evidence in demo'},identity_confidence:{available:true,value:.82,weight:.15},spatial_consistency:{available:false,value:null,weight:.1,basis:'No georeferenced source data in demo'}}};
  else if(p.startsWith('/parcels/')){const parcelRow=s.parcels.find(a=>a.id===id)||s.parcels[0];const documents=s.docs.filter(d=>d.parcel_id===parcelRow.id);const claims=documents.flatMap(claimsForDocument);const owners=[...new Set(claims.filter(c=>c.standardized_field==='owner_name').map(c=>c.field_value))];const parcel={...parcelRow,document_count:documents.length,first_seen_year:Math.min(...documents.map(d=>d.document_year)),last_seen_year:Math.max(...documents.map(d=>d.document_year))};result={parcel,documents,persons:owners.map((name,index)=>({id:index+1,canonical_name:name})),aliases:[],claims};}
  else if(p==='/investigation-cases'&&method==='get')result={cases:s.cases.filter(c=>!params.status||c.status===params.status).filter(c=>!params.parcel_id||c.parcel_id===Number(params.parcel_id)).filter(c=>!params.band||c.priority_band===params.band)};
  else if(p.startsWith('/investigation-cases/')&&method==='post'){const c=s.cases.find(x=>x.id===id);if(c){if(p.endsWith('/assign'))c.assigned_to=data?.assigned_to;if(p.endsWith('/comment'))c.comments.push({text:data?.text,created_at:new Date().toISOString()});if(p.endsWith('/resolve'))c.status='CLOSED';save(s);log('Investigation updated',{case_id:id});}result=c||{ok:true};}
  else if(p==='/gis/parcels')result={type:'FeatureCollection',features:s.parcels.map((a,i)=>({type:'Feature',geometry:{type:'Polygon',coordinates:[[[80.05+i*.003,26.85],[80.052+i*.003,26.85],[80.052+i*.003,26.852],[80.05+i*.003,26.852],[80.05+i*.003,26.85]]]},properties:{...a,parcel_id:a.id}}))};
  else if(p==='/analytics/quality')result={documents_measured:s.docs.length,measurement_note:'Illustrative browser demo values; not measured OCR performance.',by_language:[{language:'Hindi (demo)',mean_ocr_confidence:88,documents:s.docs.length}],by_document_type:[{document_type:'Khatauni',mean_extraction_confidence:82,documents:2}],evidence_grounding:{fields_with_source_region:0,fields_without_source_region:20,grounded_share_pct:0}};
  else if(p==='/analytics/throughput')result={timeline:[{day:'Mon',uploaded:5,processed:4,verified:2},{day:'Tue',uploaded:8,processed:7,verified:5},{day:'Wed',uploaded:6,processed:5,verified:3},{day:'Thu',uploaded:10,processed:8,verified:7},{day:'Fri',uploaded:7,processed:6,verified:5}],totals:{uploaded:s.docs.length,processed:s.docs.length,verified:s.records.length},processing_failures:[],human_corrections_by_field:[],total_human_corrections:0};
  else if(p==='/audit/logs')result=s.audit.slice(0,100);
  else if(p==='/notifications')result=s.notifications;
  else if(p==='/notifications/read-all'&&method==='put'){s.notifications.forEach(n=>n.is_read=true);save(s);result={ok:true};}
  else if(p==='/locations/states')result=['Uttar Pradesh','Rajasthan','Punjab','Tamil Nadu','Maharashtra','Karnataka','Bihar'].map((name,i)=>({id:i+1,name}));
  else if(/\/states\/\d+\/districts$/.test(p))result=[{id:1,name:'Kanpur Nagar'},{id:2,name:'Jaipur'},{id:3,name:'Ludhiana'},{id:4,name:'Chennai'}];
  else if(/\/districts\/\d+\/tehsils$/.test(p))result=[{id:1,name:'Bilhaur'},{id:2,name:'Sanganer'},{id:3,name:'Samrala'},{id:4,name:'Alandur'}];
  else if(/\/tehsils\/\d+\/villages$/.test(p))result=[{id:1,name:'Bilhaur Dehat'},{id:2,name:'Shivdaspura'},{id:3,name:'Manupur'},{id:4,name:'Nanganallur'}];
  else if(p==='/learning/corrections')result=[];
  else if(p==='/learning/terminology')result=[];
  else if(p==='/admin/stats'){const staff=s.users.filter(u=>u.role!=='viewer');result={total_admins:staff.length,active_admins:staff.filter(u=>u.is_active).length,inactive_admins:staff.filter(u=>!u.is_active).length};}
  else if(p==='/admin/users'&&method==='get')result=s.users.filter(u=>(!params.role||u.role===params.role)&&(params.is_active===undefined||u.is_active===String(params.is_active)));
  else if(p==='/admin/users'&&method==='post'){const u={id:Date.now(),...data,is_active:data?.is_active??true};s.users.push(u);save(s);log('Demo user created',{username:u.username,role:u.role});result=u;}
  else if(p.startsWith('/admin/users/')&&p.endsWith('/status')&&method==='put'){const u=s.users.find(x=>x.id===id);if(u)u.is_active=Boolean(data?.is_active);save(s);result=u||{ok:true};}
  else if(p.startsWith('/admin/users/')&&p.endsWith('/reset-password')&&method==='post'){const u=s.users.find(x=>x.id===id);if(u)u.password_reset_at=new Date().toISOString();save(s);result={ok:true};}
  else if(/^\/admin\/users\/\d+$/.test(p)&&method==='put'){const u=s.users.find(x=>x.id===id);if(u)Object.assign(u,data);save(s);result=u||{ok:true};}
  else if(/^\/admin\/users\/\d+$/.test(p)&&method==='delete'){s.users=s.users.filter(u=>u.id!==id);save(s);result={ok:true};}
  else if(p==='/gis/vectorize-map'&&method==='post')result={status:'VECTORIZED_UNGEOREFERENCED',parcels_detected:4,features:4,coordinates:'normalized image coordinates',geojson:{type:'FeatureCollection',features:[]},message:'Demo vectorization complete. Geometry is not georeferenced.'};
  else result={};
  return ok(result);
};
const request=(method,url,data,config={})=>demo(method,url,data,config);
const api={get:(url,config={})=>request('get',url,undefined,config),post:(url,data,config={})=>request('post',url,data,config),put:(url,data,config={})=>request('put',url,data,config),patch:(url,data,config={})=>request('patch',url,data,config),delete:(url,config={})=>request('delete',url,undefined,config)};
export default api;
